"""empty message

Revision ID: 47725eac40d4
Revises: 92f9eb99e830
Create Date: 2020-07-02 19:16:51.065174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47725eac40d4'
down_revision = '92f9eb99e830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portrait_file_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_portrait_md5', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('portrait_records', 'is_concat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portrait_records', sa.Column('is_concat', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('portrait_file_names')
    # ### end Alembic commands ###
