"""empty message

Revision ID: 92f9eb99e830
Revises: 914d00d1492a
Create Date: 2020-07-02 10:26:41.947924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f9eb99e830'
down_revision = '914d00d1492a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('check_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portrait_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('is_concat', sa.Boolean(), nullable=True),
    sa.Column('staff_portrait_prefix', sa.String(length=256), nullable=True),
    sa.Column('staff_portrait_amt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_op_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('op_code', sa.Integer(), nullable=True),
    sa.Column('op_by', sa.Integer(), nullable=True),
    sa.Column('op_content', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['op_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_op_log')
    op.drop_table('portrait_records')
    op.drop_table('attendance')
    # ### end Alembic commands ###
